#!/usr/bin/env bash
set -e # Terminate script immediately if any individual command fails

echo "================================================================="
echo "1. Extracting Debian Metadata & Generating RPM Spec File..."
echo "================================================================="
python3 generate_spec.py

# Extract name and version dynamically from debian/changelog for filesystem operations
PACKAGE_NAME=$(dpkg-parsechangelog -S Source)
PACKAGE_VERSION=$(dpkg-parsechangelog -S Version | cut -d'-' -f1)

export APP_VERSION_VALUE=$PACKAGE_VERSION

echo "Parsed Target: ${PACKAGE_NAME} (Version: ${PACKAGE_VERSION})"

echo "================================================================="
echo "2. Compiling Binaries & Building Debian Packages (.deb & .txz)..."
echo "================================================================="
# -us -uc skips GPG signing, -b builds binary architecture assets only
echo "PWD ========== $(pwd)"
dpkg-buildpackage -us -uc -b && mv ../${PACKAGE_NAME}_$PACKAGE_VERSION* ../..

echo "================================================================="
echo "3. Organizing RPM Sandboxed Workspace..."
echo "================================================================="
# Clean old build layouts to prevent asset pollution
rm -rf rpmbuild
mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

# Copy the fresh pre-compiled .txz archives generated by debian/rules
cp ../../${PACKAGE_NAME}*_${PACKAGE_VERSION}*.txz rpmbuild/SOURCES/

echo "================================================================="
echo "4. Repackaging Compiled Tarballs into Independent RPM Files..."
echo "================================================================="
# Create a local user-space RPM database to bypass root transaction locks
mkdir -p rpmbuild/db
rpmdb --initdb --dbpath "$(pwd)/rpmbuild/db"

# Execute the build task ignoring missing system dependency flags (--nodeps)
rpmbuild --define "_topdir $(pwd)/rpmbuild" \
         --define "_dbpath $(pwd)/rpmbuild/db" \
         --nodeps -bb "${PACKAGE_NAME}.spec"

echo "================================================================="
echo "5. Execution Complete! Summary of Generated Packages:"
echo "================================================================="
echo ">>> DEBIAN PACKAGES (In parent directory):"
ls -hl ../../${PACKAGE_NAME}*${PACKAGE_VERSION}*.deb
echo ""
echo ">>> RPM PACKAGES (In parent directory):"
cp rpmbuild/RPMS/*.rpm ../../
ls -hl ../../${PACKAGE_NAME}*${PACKAGE_VERSION}*.rpm
echo ""
echo ">>> TAR PACKAGES (In parent directory):"
ls -hl ../../${PACKAGE_NAME}*${PACKAGE_VERSION}*.txz
